import Head from 'next/head'
import Header from '../components/Header'
import Image from 'next/image'
import {FaSearch, FaMicrophone} from 'react-icons/fa'
import Footer from '../components/Footer'
import {useRouter} from 'next/router'
import {useRef} from 'react'

export default function Home() {
  const router = useRouter()
  const searchInputRef = useRef(null)

  const search = (e) => {
      e.preventDefault()
      const term = searchInputRef.current.value
    if(!term.trim()) return
      router.push(`/search?term=${term.trim()}`)
  }

  return (
    <div>
      <Head>
        <title>Google v3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
        <Header />
      {/* Body */}

      <form className="flex flex-col items-center mt-40">
        <Image src="https://cdn.vox-cdn.com/thumbor/Pkmq1nm3skO0-j693JTMd7RL0Zk=/0x0:2012x1341/1200x800/filters:focal(0x0:2012x1341)/cdn.vox-cdn.com/uploads/chorus_image/image/47070706/google2.0.0.jpg" 
        width="300" height="100" objectFit="cover" />
        <div className="flex w-full mt-5 mx-auto max-w-[90%] border border-gray-200 hover:shadow-lg focus-within:shadow-lg px-5 py-3 rounded-full items-center sm:max-w-xl lg:max-w-2xl">
          <FaSearch className="h-5 text-gray-500 mr-3" />
          <input ref={searchInputRef} type="text" className="flex-grow focus:outline-none" />
          <FaMicrophone className="h-5"/>
        </div>
        <div className="flex flex-col sm:flex-row w-[50%] space-y-2 mt-8 sm:space-y-0 sm:space-x-4 justify-center">
          <button onClick={search} className="btn">Google Search</button>
        <button className="btn">I'm Feeling Lucky</button>
        </div>
        
      </form>

      <Footer />

    </div>
  )
}
